#!/bin/sh

# XEP Graphical Aide

XEP_HOME="/Users/dave/BS2/Common/ThirdPartyTools/XEP"
JAVA_HOME="/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home"
CP="$XEP_HOME/lib/xep.jar:\
$XEP_HOME/lib/x4u.jar:\
$XEP_HOME/lib/saxon6.5.5/saxon.jar:\
$XEP_HOME/lib/saxon6.5.5/saxon-xml-apis.jar:\
$XEP_HOME/lib/xt.jar:\
$XEP_HOME/lib/crimson.jar"

"$JAVA_HOME/bin/java" \
	"-Dcom.renderx.xep.CONFIG=$XEP_HOME/xep.xml" \
	-cp "$CP" \
	com.renderx.xepx.x4u.as.Assistant "$@"
