#!/bin/sh

# XEP command-line

JAVA_HOME="/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home"
XEP_HOME="/Users/dave/BS2/Common/ThirdPartyTools/XEP"

CP="$JAVA_HOME/lib/tools.jar:\
$XEP_HOME/lib/xep.jar:\
$XEP_HOME/lib/saxon6.5.5/saxon.jar:\
$XEP_HOME/lib/saxon6.5.5/saxon-xml-apis.jar:\
$XEP_HOME/lib/xt.jar"

"$JAVA_HOME/bin/java" \
	-classpath "$CP" \
	"-Dcom.renderx.xep.CONFIG=$XEP_HOME/xep.xml" \
	com.renderx.xep.XSLDriver "$@" 

