source 'https://rubygems.org'

gem 'coderay', "0.9.7"
gem 'kramdown'
gem 'nokogiri'
gem 'ritex'
gem 'builder'
gem 'rouge', "~>3"
gem 'RedCloth'

gem "ox",         "~> 2.14"
gem "faraday",    "~> 2.7"
gem "image_size", "~> 3.3"
gem "ansi",       "~> 1.5"
